# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

$:.push File.expand_path("../lib", __FILE__)

require "date"
require "streamly_ffi/version"

Gem::Specification.new do |s|
  s.name            = "streamly_ffi"
  s.version         = StreamlyFFI::VERSION
  s.summary         = %q{A streaming Curl/HTTP/REST client for Ruby, in cross-Ruby FFI.}
  s.description     = %q{A streaming Curl/HTTP/REST client for Ruby, in cross-Ruby FFI. Using the CurlFFI RubyGem.}
  s.authors         = ["Brian Lopez", "Scott Gonyea"]
  s.date            = Date.today.to_s
  s.email           = %q{seniorlopez@gmail.com}
  s.homepage        = %q{http://github.com/aitrus/streamly_ffi}

  s.add_dependency              "curl_ffi"
  s.add_development_dependency  "rspec"

  s.files           = `git ls-files`.split("\n")
  s.test_files      = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.require_paths   = ["lib"]
end

